### ISSUE TITLE
Win10系统设置自动隐藏任务栏后的显示问题

### ISSUE THREAD

**Issue by Fb-dtalker** [Jason-Ma-233/Sakura_DesktopMascot#1]
您好，
我在使用Sakura_DesktopMascot的时候遇到了两个问题：

    1，当我尝试将鼠标移动到隐藏状态下的任务栏时，它并不会照常弹出。(当然按win键能够出现)

    2，请问您是否有注意到在将Unity窗口的标题栏用
           SetWindowLong(windowHandle, GWL_STYLE, WS_POPUP | WS_VISIBLE | WS_EX_TOPMOST);
          语句隐藏之后，鼠标的位置判定在y轴的方向会往下多移动一段距离？
          并且我发现偏移的距离会随着鼠标所在点与窗口最高处距离的增大而增大。

          因为我也在尝试使用Unity来制作桌宠，而我的项目中用到了UGUI按钮所以发现了这个问题。

电脑信息：
Win10家庭版的1903版本，64位

设置：
电脑自动隐藏任务栏

**Comment by Jason-Ma-233** [comment]
自动隐藏任务栏可能涉及实时更新窗口大小，现版本只在启动时设置窗口大小位置，有空时考虑修一下

**Comment by Fb-dtalker** [comment]
好的，感谢您的回复。

另外，刚刚发现问题2中的偏移问题可以通过在启动时增加参数 -popupwindow 解决，如果您的项目以后发现这样的问题可以考虑这个解决方法。
